from __future__ import annotations


STRATEGY_CATALOG = {
    "objectives": [
        {"value": "goal", "label": "Gol"},
        {"value": "corner", "label": "Corner"},
        {"value": "card", "label": "Tarjeta"},
    ],
    "subjects": [
        {"value": "home", "label": "Equipo local"},
        {"value": "away", "label": "Equipo visitante"},
        {"value": "either", "label": "Cualquiera"},
        {"value": "prematch_favorite", "label": "Favorito pre-partido (especializado)"},
    ],
    "operators": [">=", ">", "=", "<=", "<", "!=", "BETWEEN"],
    "windows": [5, 10, 15],
    "metrics": [
        {"value": "minute", "label": "Minuto", "group": "Partido", "type": "number", "supports_window": False},
        {"value": "home_is_losing", "label": "Va perdiendo · Local", "group": "Partido", "type": "boolean", "supports_window": False},
        {"value": "away_is_losing", "label": "Va perdiendo · Visitante", "group": "Partido", "type": "boolean", "supports_window": False},
        {"value": "score_difference_home", "label": "Diferencia de goles · Local", "group": "Partido", "type": "number", "supports_window": False},
        {"value": "score_difference_away", "label": "Diferencia de goles · Visitante", "group": "Partido", "type": "number", "supports_window": False},
        {"value": "home_odds", "label": "Cuota pre-partido · Local", "group": "Pre-partido", "type": "number", "supports_window": False},
        {"value": "draw_odds", "label": "Cuota pre-partido · Empate", "group": "Pre-partido", "type": "number", "supports_window": False},
        {"value": "away_odds", "label": "Cuota pre-partido · Visitante", "group": "Pre-partido", "type": "number", "supports_window": False},
        {"value": "home_probability", "label": "Probabilidad normalizada · Local", "group": "Pre-partido", "type": "number", "supports_window": False},
        {"value": "away_probability", "label": "Probabilidad normalizada · Visitante", "group": "Pre-partido", "type": "number", "supports_window": False},
        {"value": "shots_home", "label": "Tiros · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "shots_away", "label": "Tiros · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "shots_on_target_home", "label": "Tiros a puerta · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "shots_on_target_away", "label": "Tiros a puerta · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "shots_off_target_home", "label": "Tiros fuera · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "shots_off_target_away", "label": "Tiros fuera · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "attacks_home", "label": "Ataques · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "attacks_away", "label": "Ataques · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "dangerous_attacks_home", "label": "Ataques peligrosos · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "dangerous_attacks_away", "label": "Ataques peligrosos · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "corners_home", "label": "Corners · Local", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "corners_away", "label": "Corners · Visitante", "group": "Estadísticas", "type": "number", "supports_window": True},
        {"value": "possession_home", "label": "Posesión · Local", "group": "Estadísticas", "type": "number", "supports_window": False},
        {"value": "possession_away", "label": "Posesión · Visitante", "group": "Estadísticas", "type": "number", "supports_window": False},
        {"value": "yellow_cards_home", "label": "Tarjetas amarillas · Local", "group": "Estadísticas", "type": "number", "supports_window": False},
        {"value": "yellow_cards_away", "label": "Tarjetas amarillas · Visitante", "group": "Estadísticas", "type": "number", "supports_window": False},
        {"value": "red_cards_home", "label": "Tarjetas rojas · Local", "group": "Estadísticas", "type": "number", "supports_window": False},
        {"value": "red_cards_away", "label": "Tarjetas rojas · Visitante", "group": "Estadísticas", "type": "number", "supports_window": False},
    ],
    "alert_fields": [
        {"value": "score", "label": "Marcador"},
        {"value": "prematch_odds", "label": "Cuota pre-partido"},
        {"value": "shots", "label": "Tiros"},
        {"value": "shots_on_target", "label": "Tiros a puerta"},
        {"value": "attacks", "label": "Ataques"},
        {"value": "dangerous_attacks", "label": "Ataques peligrosos"},
        {"value": "corners", "label": "Corners"},
        {"value": "possession", "label": "Posesión"},
        {"value": "cards", "label": "Tarjetas"},
    ],
}
