"""initial application schema

Revision ID: 18bd61ee1ee5
Revises: 
Create Date: 2026-09-06 22:55:51.944774
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '18bd61ee1ee5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('record_id', sa.String(length=260), nullable=False),
    sa.Column('fixture_id', sa.String(length=80), nullable=False),
    sa.Column('strategy_key', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('rule_status', sa.String(length=20), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_triggered', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Boolean(), nullable=True),
    sa.Column('censored_reason', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_backtest_results_fixture_id'), 'backtest_results', ['fixture_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_match_id', sa.String(length=80), nullable=False),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league_id', sa.String(length=80), nullable=False),
    sa.Column('league_name', sa.String(length=160), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('home_team_name', sa.String(length=160), nullable=False),
    sa.Column('away_team_name', sa.String(length=160), nullable=False),
    sa.Column('favorite_side', sa.String(length=8), nullable=False),
    sa.Column('favorite_odds', sa.Float(), nullable=False),
    sa.Column('favorite_probability', sa.Float(), nullable=False),
    sa.Column('bookmaker_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_match_id', name='uq_match_provider_id')
    )
    op.create_index('ix_matches_kickoff', 'matches', ['kickoff_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=220), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('fixture_id', sa.String(length=80), nullable=False),
    sa.Column('strategy_key', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('minute_extra', sa.Integer(), nullable=True),
    sa.Column('favorite_team_name', sa.String(length=160), nullable=False),
    sa.Column('score_favorite', sa.Integer(), nullable=False),
    sa.Column('score_opponent', sa.Integer(), nullable=False),
    sa.Column('delivery_status', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index('ix_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_fixture_id'), 'alerts', ['fixture_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('minute_extra', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score_home', sa.Integer(), nullable=True),
    sa.Column('score_away', sa.Integer(), nullable=True),
    sa.Column('shots_home', sa.Integer(), nullable=True),
    sa.Column('shots_away', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_home', sa.Integer(), nullable=True),
    sa.Column('shots_on_target_away', sa.Integer(), nullable=True),
    sa.Column('corners_home', sa.Integer(), nullable=True),
    sa.Column('corners_away', sa.Integer(), nullable=True),
    sa.Column('possession_home', sa.Float(), nullable=True),
    sa.Column('possession_away', sa.Float(), nullable=True),
    sa.Column('xg_home', sa.Float(), nullable=True),
    sa.Column('xg_away', sa.Float(), nullable=True),
    sa.Column('red_cards_home', sa.Integer(), nullable=True),
    sa.Column('red_cards_away', sa.Integer(), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'captured_at', name='uq_snapshot_match_time')
    )
    op.create_index('ix_snapshots_match_captured', 'snapshots', ['match_id', 'captured_at'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('strategy_key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('statistical_status', sa.String(length=20), nullable=False),
    sa.Column('objective_type', sa.String(length=60), nullable=False),
    sa.Column('objective_subject', sa.String(length=80), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_key', 'version', name='uq_strategy_version')
    )
    op.create_index(op.f('ix_strategies_strategy_key'), 'strategies', ['strategy_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategies_strategy_key'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index('ix_snapshots_match_captured', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_alerts_fixture_id'), table_name='alerts')
    op.drop_index('ix_alerts_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_matches_kickoff', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_backtest_results_fixture_id'), table_name='backtest_results')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
