"""add notification destinations and deliveries

Revision ID: 6e278b374478
Revises: 18bd61ee1ee5
Create Date: 2026-09-06 23:28:06.553959
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6e278b374478'
down_revision: Union[str, None] = '18bd61ee1ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=180), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'channel', 'destination', name='uq_notification_destination')
    )
    op.create_index(op.f('ix_notification_endpoints_owner_id'), 'notification_endpoints', ['owner_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=220), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=240), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['endpoint_id'], ['notification_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'endpoint_id', name='uq_alert_endpoint_delivery')
    )
    op.create_index('ix_notification_delivery_status', 'notification_deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_delivery_status', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_notification_endpoints_owner_id'), table_name='notification_endpoints')
    op.drop_table('notification_endpoints')
    # ### end Alembic commands ###
